---
title: "AWRA Figures"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{AWRA Figures}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
library(CSLSlevels)
library(lubridate)
library(dplyr)
library(ggplot2)
library(patchwork)
library(extrafont)

lakes           <- c("Pleasant", "Long", "Plainfield")
csls_levels     <- CSLSlevels::csls_levels
csls_levels_all <- csls_levels %>% filter(.data$lake %in% lakes)
csls_levels_all$lake <- factor(csls_levels_all$lake, levels = lakes)
csls_levels     <- csls_levels_all %>% 
                   filter(year(date) <= 2018, year(date) >= 1981)

text_size <- 24
```

```{r plots, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=12, fig.height=5}
p1 <- plot_levels(csls_levels_all, text_size = text_size)
p2 <- plot_levels(csls_levels, text_size = text_size, npretty_breaks = 3)
p2a <- plot_levels(csls_levels, text_size = text_size, npretty_breaks = 3, probs = 90)
p2b <- plot_levels(csls_levels, text_size = text_size, npretty_breaks = 3, probs = 10)
p2c <- plot_levels(csls_levels, text_size = text_size, npretty_breaks = 3, probs = 50)
p3 <- plot_frequency(csls_levels, text_size = text_size)
p3a <- plot_frequency(csls_levels, text_size = text_size, probs = 90)
p3b <- plot_frequency(csls_levels, text_size = text_size, probs = 10)
p3c <- plot_frequency(csls_levels, text_size = text_size, probs = 50)
p4a <- plot_duration(csls_levels_all, 
                     probs = 90, 
                     show_median = FALSE,
                     text_size = text_size)
p4b <- plot_duration(csls_levels_all, 
                     probs = 10, 
                     show_median = FALSE,
                     text_size = text_size)
p4am <- plot_duration(csls_levels_all, 
                     probs = 90, 
                     show_median = TRUE,
                     text_size = text_size)
p4bm <- plot_duration(csls_levels_all, 
                     probs = 10, 
                     show_median = TRUE,
                     text_size = text_size)
p5a <- plot_rate_change(csls_levels, lag_months = 1, text_size = text_size)
p5b <- plot_rate_change(csls_levels, lag_months = 3, text_size = text_size)
p5c <- plot_rate_change(csls_levels, 
                        lag_months = 12, 
                        text_size = text_size)
p6 <- plot_timing(csls_levels, text_size = text_size, npretty_breaks = 3)
```



```{r save01, eval=FALSE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=12, fig.height=5}
ggsave(filename = "levels_all_wide.png",
       plot = p1,
       path = "doc/figures",
       width = 13,
       height = 6,
       units = "in")
ggsave(filename = "levels_all.png",
       plot = p1,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "levels_wide.png",
       plot = p2,
       path = "doc/figures",
       width = 13,
       height = 6,
       units = "in")
ggsave(filename = "levels.png",
       plot = p2,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "levels_90.png",
       plot = p2a,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "levels_10.png",
       plot = p2b,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "levels_50.png",
       plot = p2c,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "magnitudes.png",
       plot = p3,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "magnitudes_90.png",
       plot = p3a,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "magnitudes_10.png",
       plot = p3b,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "magnitudes_50.png",
       plot = p3c,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "durations_90.png",
       plot = p4a,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "durations_10.png",
       plot = p4b,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "durations_90_median.png",
       plot = p4am,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "durations_10_median.png",
       plot = p4bm,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "rate_of_change_1mo.png",
       plot = p5a,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "rate_of_change_3mo.png",
       plot = p5b,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "rate_of_change_12mo.png",
       plot = p5c,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
ggsave(filename = "timing_months.png",
       plot = p6,
       path = "doc/figures",
       width = 13,
       height = 3.5,
       units = "in")
```

```{r veg_stuff, eval=FALSE, echo=FALSE}
library(sp)
library(raster)
library(sf)
library(NISTunits)
library(reshape2)
library(dplyr)
library(ggplot2)
library(extrafont)
library(stats)


lake <- "Plainfield"
depth_int    <- 0.1
wetland_dry  <- 
text_size <- 24
line_size <- 1.5
probs     <- c(10, 90)
veg_names <- c("Upland", "Wetland", "Wetland/Aquatic", "Aquatic")
veg_depths <- c(-NISTunits::NISTftTOmeter(1), 0, 2)
diff <- 1.8 #0.2

# Lake levels (historical estimate + recent data)
historic_levels <- CSLSlevels::csls_levels
recent_levels   <- CSLSdata::lake_levels[[lake]]$level_m

# Lake level exceedances
yintercept <- data.frame(NULL)
for (exceedance in probs) {
  lake_levels <- historic_levels %>% filter(.data$lake == !!lake)
  ranked      <- calculate_probs_of_levels(lake_levels)
  level       <- calculate_levels_at_probs(ranked, exceedance)$level
  yintercept  <- rbind(yintercept, cbind(level, exceedance))
}
yintercept  <- yintercept %>%
               mutate(yintercept = as.numeric(as.character(.data$level)))

# Maxiumum lake level
max_estimate   <- max(historic_levels$level_pred[which(historic_levels$lake == lake)])
max_data       <- max(recent_levels, na.rm = TRUE)
max_elev       <- round(max(max_estimate, max_data), 2)

# Minimum lake level (i.e., bone dry)
this_raster    <- CSLSlevels::lake_raster[[lake]]
min_elev       <- round(minValue(this_raster), 2)

# Round up max contour
max_elev       <- max_elev - NISTunits::NISTftTOmeter(1)
max_contour    <- min_elev + depth_int*ceiling((max_elev - min_elev)/depth_int)

# Outline of lake
outline       <- rasterToContour(this_raster, levels = max_contour)
outline_sf    <- st_as_sf(outline)
outline_poly  <- st_polygonize(outline_sf)

# Contours of lake levels
lake_levels    <- seq(min_elev, max_contour, depth_int)
contours       <- rasterToContour(this_raster, levels = lake_levels)
contours_sf    <- st_as_sf(contours)
contours_poly  <- st_polygonize(contours_sf)
contours_poly  <- contours_poly[order(contours_poly$level, decreasing = TRUE),]
areas_poly     <- st_area(contours_poly)


# Area of land less than or equal to elevation
elev_area   <- data.frame(elev = as.numeric(as.character(contours_poly$level)),
                             area = as.numeric(areas_poly))
f_elev_area <- approxfun(x = elev_area$elev,
                         y = elev_area$area)

# Vegetation elevations
veg_elevs     <- as.data.frame(elev_area$elev)
veg_elevs[,2] <- max_contour
for (i in 1:length(veg_depths)) {
  veg_elevs[,i+2] <- veg_elevs$elev - veg_depths[i]
}
veg_elevs[veg_elevs > max_contour] <- max_contour
colnames(veg_elevs) <- c("elev", veg_names)

veg_areas <- veg_elevs
for (i in 1:length(veg_names)) {
  veg_areas[,i+1] <- f_elev_area(veg_elevs[,i+1])
}
veg_areas[is.na(veg_areas)] <- 0

veg_incr_areas <- veg_areas
for (i in 2:(ncol(veg_incr_areas)-1)) {
  veg_incr_areas[,i] <- veg_incr_areas[,i] - veg_incr_areas[,i+1]
}

veg_frac_areas <- veg_incr_areas
veg_frac_areas[,2:ncol(veg_frac_areas)] <- veg_frac_areas[,2:ncol(veg_frac_areas)]/veg_areas[1,2]
veg_frac_areas$Wetland <- veg_frac_areas$Wetland + veg_frac_areas$`Wetland/Aquatic`
veg_frac_areas$Aquatic <- veg_frac_areas$Aquatic + veg_frac_areas$`Wetland/Aquatic`
veg_frac_areas$`Wetland/Aquatic` <- NULL

vegetation <- melt(veg_frac_areas, id.vars = "elev")
vegetation <- vegetation %>% arrange(.data$elev)

# Blank plot
plot_obj <- ggplot(data = vegetation) +
            geom_blank(aes(x = value, y = elev)) +
            facet_grid(~variable) +
            scale_y_continuous(expand = c(0,0)) +
            scale_x_continuous(limits = c(0, 1),
                               expand = c(0,0),
                               labels = scales::percent) +
           labs(x = "Lake Area with Suitable Habitat",
                y = "Lake Elevation (m)") +
           theme_bw() +
           theme(text = element_text(family = "Segoe UI Semilight",
                                     size = text_size),
                 plot.title = element_text(hjust = 0.5),
                 panel.grid.minor = element_blank(),
                 panel.spacing.x = unit(14, "mm"),
                 legend.position = "none")

# Add lines
plot_obj <- ggplot(data = vegetation) +
            geom_path(aes(x = value, y = elev, color = variable),
                      size = line_size) +
            facet_grid(~variable) +
            scale_y_continuous(expand = c(0,0)) +
            scale_x_continuous(limits = c(0, 1),
                               expand = c(0,0),
                               labels = scales::percent) +
            scale_color_manual(values = c("#B15928", "#33A02C", "#1F78B4")) +
            labs(x = "Lake Area with Suitable Habitat",
                 y = "Lake Elevation (m)") +
            theme_bw() +
            theme(text = element_text(family = "Segoe UI Semilight",
                                      size = text_size),
                  plot.title = element_text(hjust = 0.5),
                  panel.grid.minor = element_blank(),
                  panel.spacing.x = unit(14, "mm"),
                  legend.position = "none")
plot_obj <- plot_obj +
            geom_hline(aes(yintercept = yintercept),
                       as.data.frame(yintercept),
                       color = "grey70",
                       linetype = "dashed",
                       size = line_size) +
            geom_hline(aes(yintercept = yintercept - diff),
                       as.data.frame(yintercept),
                       color = "#c00000",
                       linetype = "dashed",
                       size = line_size)

ggsave(filename = "lake_veg04_large.png",
       plot = plot_obj,
       path = "doc/figures",
       width = 10.7,
       height = 5,
       units = "in")

# Outline Only for lake
plot_outline <- plot_lake_contours("Plainfield", 
                                   max_contour, 
                                   color_labels = c(""), 
                                   color_values = "black")
plot_outline <- plot_outline +
                theme_void() +
                theme(legend.position = "none")
ggsave(filename = "pfl_outline.png",
       plot = plot_outline,
       path = "doc/figures",
       width = 2.5,
       height = 1.25,
       units = "in")


# Veg fill
elev <- yintercept$yintercept[2] - diff
lake_levels <- max_contour
for (i in 1:length(veg_depths)) {
  lake_levels <- c(lake_levels, elev - veg_depths[i])
}
contours       <- rasterToContour(this_raster, levels = lake_levels)
contours_sf    <- st_as_sf(contours)
contours_poly  <- st_polygonize(contours_sf)
contours_poly  <- contours_poly[order(contours_poly$level, decreasing = TRUE),]

plot_obj    <- ggplot() +
               layer_spatial(data = outline,
                             color = "black",
                             fill = NA)
for (i in 1:length(contours_poly$level)) {
  plot_obj  <- plot_obj +
               layer_spatial(data = contours_poly[i,],
                             aes(fill = .data$level),
                             color = NA,
                             size = line_size)
}
if (length(contours_poly$level) == 4) {
  plot_obj    <- plot_obj + 
                 scale_fill_manual(name = "",
                                   values = c("#1F78B4", "#B2DF8A", "#33A02C", "#B15928"),
                                   labels = rev(veg_names)) +
                 labs(title = "",
                      fill = veg_names,
                      x = "", y = "") +
                 theme_void() +
                 theme(legend.position = "none")
} else {
  plot_obj    <- plot_obj + 
                 scale_fill_manual(name = "",
                                   values = c("#B2DF8A", "#33A02C", "#B15928"),
                                   labels = rev(veg_names)) +
                 labs(title = "",
                 fill = veg_names,
                 x = "", y = "") +
                 theme_void() +
                 theme(legend.position = "none")
}

ggsave(filename = "pfl_veg_p90_large.png",
       plot = plot_obj,
       path = "doc/figures",
       width = 3.1,
       height = 1.55,
       units = "in")




lake_levels <- veg_elevs[13,2:4]
plot_lake_contours("Plainfield", lake_levels, color_labels = c("Upland", "Wetland", "Aquatic"), color_values = c("#1F78B4", "#B2DF8A", "#B15928"))

lake_levels <- veg_elevs[21,2:4]
plot_lake_contours("Plainfield", lake_levels, color_labels = c("Upland", "Wetland", "Aquatic"), color_values = c("#1F78B4", "#B2DF8A", "#B15928"))

lake_levels <- veg_elevs[35,2:4]
plot_lake_contours("Plainfield", lake_levels, color_labels = c("Upland", "Wetland"), color_values = c("#B2DF8A", "#B15928"))

```
