#' CV and mean of number of annual occurences of extreme levels
#'
#' Given the cslsLevels data frame, calculate the percentage of years in which
#' the lake spends at least one month beyond given exceedance probabilities
#'
#' @param lakeName Name of the lake of interest without "lake", e.g.
#'                 "Plainfield", "Long", or "Pleasant"
#' @param exceeds The exceedance probabilities of interest, as a vector of
#'                values between 0 and 1
#' @param startDate Specify a range of dates by which to filter lake level
#'                  predictions
#' @param endDate Specify a range of dates by which to filter lake level
#'                predictions
#'
#' @return a list of the following:
#' \item{result}{A data frame of one column, with mean and cv for each
#'               exceedance supplied, with appropriate row names}
#' \item{df}{The data frame generated by hi_lo_duration() that was used by this
#'           function}
#'
#' @import magrittr
#' @import stats
#'
#' @export


hi_lo_ann <- function(lakeName,
                      exceeds = c(0.1, 0.25, 0.75, 0.9),
                      startDate = "1905-01-01",
                      endDate = "2019-12-01") {

  aa <- hi_lo_duration(lakeName = lakeName,
                       exceeds = exceeds,
                       startDate = startDate,
                       endDate = endDate)$ll_hi_lo

  aa$year <- substr(aa$date, 1,4) %>% as.numeric()
  aa$month <- substr(aa$date, 6,7) %>% as.numeric()
  aa$mCount <- (aa$year - min(aa$year))*12 + aa$month
  aa$year %<>% factor(levels = c(min(aa$year):max(aa$year)))

  result <- data.frame(names = character(0),
                       vals = numeric(0))
  countTables <- list()

  for (e in paste0(exceeds*100, "%")) {
    bb <- aa[aa[[e]] == 1, ]
    # bb$diff <- c(99, diff(bb$mCount, 1))
    # bb <- bb[bb$diff != 1, ]

    countTables[[e]] <- table(table(unique(bb$year)))

    mean <- mean(table(unique(bb$year)))
    cv <- 100*sd(table(unique(bb$year)))/mean(table(unique(bb$year)))

    r <- data.frame(names = c(paste0("mean_", e),
                              paste0("cv_", e)),
                    vals = c(mean, cv))

    result <- rbind(result, r)
  }

  rownames(result) <- result$names
  result$names <- NULL
  colnames(result) <- lakeName
  return(list(result = result,
              df = aa,
              countTables = countTables))
}
